# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Generate Agenda Database

on:
  push:
    branches: ["test-actions"] # FIXME: replace with 'main'
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.8.3 
          poetry install --with dev
          poetry update
      - name: Download previous agenda from artefact repo
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: agendas.db
          path: ./agendas.db
      - name: Display file structure
        run: ls -R
      - name: Generate new agenda
        run: |
          poetry run python ./aus_council_scrapers/main.py --council melbourne
      - name: Upload new agenda to artefact repo
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          name: agendas.db
          path: |
            ./agendas.db
